export const types = {
    GET_URLS: "GET_URLS",
    POST_URL: "POST_URL",
    DELETE_URL: "DELETE_URL",
    GET_HASH: "GET_HASH",
    SHOW_NOTIFICATION: "SHOW_NOTIFICATION",
    HIDE_NOTIFICATION: "HIDE_NOTIFICATION"
};
